spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testDb

  jpa:
    ddl-auto: create
    show-sql: true
    properties:
      format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 20000MB

file:
  dir: /Users/sungjin/toy-project/file/
